### PR TITLE
Create README.md

### LINKED ISSUE #1: Create helpful README

### PR DESCRIPTION
**Pull request by jasoncpatton**
When complete, resolves #1 .

### CODE REVIEW

**Comment by bbockelm** [comment]
@jasoncpatton - what's the status here?

**Comment by jasoncpatton** [comment]
Circling back to this soon now that HTCondor 8.8.1 has frozen. Will include config changes made.

**Review by bbockelm — CHANGES_REQUESTED** [review]
Please separate out the `setup.py` changes into a standalone commit.

**Comment by bbockelm** [comment]
@matyasselmeci - please review the documentation here as part of your OSG SciTokens work... potentially useful for you to try setting up one of your own instances.

**Comment by jasoncpatton** [comment]
> Please separate out the `setup.py` changes into a standalone commit.

Done. `setup.py` changes merged in master.

**Comment by bbockelm** [comment]
@jasoncpatton - items in review addressed.  Please re-review.

**Review by bbockelm — APPROVED** [review]
LGTM.

We'll need to re-adjust the README after we get the packaging done, but gotta start somewhere...

**Pull request merged**
