### PR TITLE
Add simple RPM package of the credmon.

### PR DESCRIPTION
**Pull request by bbockelm**
Bare minimum generated by the pyp2rpm program; still significant configuration needed that is not included in `setup.py`.

### CODE REVIEW

**Review by jasoncpatton — COMMENTED** [review]
Per https://github.com/htcondor/scitokens-credmon/pull/12#pullrequestreview-201610080 should we also have `python-scitokens` required here?

**Comment by jasoncpatton** [comment]
And `python-crypto` for the cryptography library.

**Comment by bbockelm** [comment]
@jasoncpatton - in the future, can you please use GitHub's "review" mechanism instead of leaving a comment?  That way, I can mark individual comments as resolved as I fix things.

Thanks!

**Comment by jasoncpatton** [comment]
Will do!

**Pull request merged**
